import { defineCollection } from "astro:content";
import { file, glob } from "astro/loaders";
import { docsLoader } from "@astrojs/starlight/loaders";
import { docsSchema } from "@astrojs/starlight/schema";
import { z } from "astro/zod";

const localizedField = z.union([
  z.string(),
  z.object({
    fr: z.string().optional(),
    en: z.string().optional(),
  }),
]);

const eventDate = z.union([
  z.string(),
  z.object({
    start: z.string(),
    end: z.string().optional(),
  }),
]);

const events = defineCollection({
  loader: file("src/data/events.yaml"),
  schema: z.object({
    id: z.string(),
    date: eventDate,
    title: localizedField,
    description: localizedField.optional(),
    location: localizedField.optional(),
    source: z.string().optional(),
  }),
});

// One entry per released stack, generated by scripts/build-stack.mjs.
// See src/types/stack.ts for the rendering-side shapes.
const chartRef = z.object({
  name: z.string(),
  version: z.string().nullable(),
  repository: z.string().nullable(),
  origin: z.enum(["upstream", "okdp", "local"]),
});

const imageRef = z.object({ repository: z.string(), tag: z.string() });

const stacks = defineCollection({
  loader: glob({ pattern: "*.yaml", base: "src/data/stack" }),
  schema: z.object({
    stack: z.string(),
    generated: z.object({
      by: z.string(),
      note: z.string(),
      sources: z.record(
        z.object({
          sha: z.string(),
          date: z.string().nullable(),
          url: z.string(),
        }),
      ),
    }),
    components: z.array(
      z.object({
        id: z.string(),
        name: z.string(),
        section: z.enum(["data-services", "control-plane", "dependencies"]),
        upstreamVersion: z.string(),
        upstreamVersionSource: z.string(),
        package: z.object({ repository: z.string(), tag: z.string() }),
        provenance: z.array(
          z.enum(["upstream-chart", "okdp-chart", "okdp-image"]),
        ),
        protected: z.boolean(),
        description: localizedField.nullable(),
        primaryChart: chartRef.nullable(),
        primaryImage: imageRef.nullable(),
        charts: z.array(chartRef),
        images: z.array(imageRef),
        modules: z.array(
          z.object({
            name: z.string(),
            charts: z.array(chartRef),
            images: z.array(imageRef),
          }),
        ),
        links: z.object({
          upstream: z.string().nullable(),
          source: z.string(),
        }),
        logo: z.string().nullable(),
      }),
    ),
  }),
});

export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
  events,
  stacks,
};
